import { User } from "@/types/Auth";

export const users: User[] = [
    {
        id: 1,
        name: "John Doe",
        first_name: "John",
        last_name: "Doe",
        name_ar: "جون دو",
        first_name_ar: "جون",
        last_name_ar: "دو",
        email: "john.doe@example.com",
    },
    {
        id: 2,
        name: "Alice Smith",
        first_name: "Alice",
        last_name: "Smith",
        name_ar: "أليس سميث",
        first_name_ar: "أليس",
        last_name_ar: "سميث",
        email: "alice.smith@example.com",
    },
    {
        id: 3,
        name: "Omar Khalid",
        first_name: "Omar",
        last_name: "Khalid",
        name_ar: "عمر خالد",
        first_name_ar: "عمر",
        last_name_ar: "خالد",
        email: "omar.khalid@example.com",
    },
    {
        id: 4,
        name: "Sophia Lee",
        first_name: "Sophia",
        last_name: "Lee",
        name_ar: "صوفيا لي",
        first_name_ar: "صوفيا",
        last_name_ar: "لي",
        email: "sophia.lee@example.com",
    },
    {
        id: 5,
        name: "Mohammed Ali",
        first_name: "Mohammed",
        last_name: "Ali",
        name_ar: "محمد علي",
        first_name_ar: "محمد",
        last_name_ar: "علي",
        email: "mohammed.ali@example.com",
    },
    {
        id: 6,
        name: "Emma Watson",
        first_name: "Emma",
        last_name: "Watson",
        name_ar: "إيما واتسون",
        first_name_ar: "إيما",
        last_name_ar: "واتسون",
        email: "emma.watson@example.com",
    },
    {
        id: 7,
        name: "Ahmed Hassan",
        first_name: "Ahmed",
        last_name: "Hassan",
        name_ar: "أحمد حسن",
        first_name_ar: "أحمد",
        last_name_ar: "حسن",
        email: "ahmed.hassan@example.com",
    },
    {
        id: 8,
        name: "Mia Chen",
        first_name: "Mia",
        last_name: "Chen",
        name_ar: "ميا تشين",
        first_name_ar: "ميا",
        last_name_ar: "تشين",
        email: "mia.chen@example.com",
    },
    {
        id: 9,
        name: "Yousef Nassar",
        first_name: "Yousef",
        last_name: "Nassar",
        name_ar: "يوسف نصار",
        first_name_ar: "يوسف",
        last_name_ar: "نصار",
        email: "yousef.nassar@example.com",
    },
    {
        id: 10,
        name: "Liam Wilson",
        first_name: "Liam",
        last_name: "Wilson",
        name_ar: "ليام ويلسون",
        first_name_ar: "ليام",
        last_name_ar: "ويلسون",
        email: "liam.wilson@example.com",
    },
    {
        id: 11,
        name: "Layla Karim",
        first_name: "Layla",
        last_name: "Karim",
        name_ar: "ليلى كريم",
        first_name_ar: "ليلى",
        last_name_ar: "كريم",
        email: "layla.karim@example.com",
    },
    {
        id: 12,
        name: "Noah Parker",
        first_name: "Noah",
        last_name: "Parker",
        name_ar: "نوح باركر",
        first_name_ar: "نوح",
        last_name_ar: "باركر",
        email: "noah.parker@example.com",
    },
    {
        id: 13,
        name: "Hana Rashid",
        first_name: "Hana",
        last_name: "Rashid",
        name_ar: "هنا رشيد",
        first_name_ar: "هنا",
        last_name_ar: "رشيد",
        email: "hana.rashid@example.com",
    },
    {
        id: 14,
        name: "Daniel Carter",
        first_name: "Daniel",
        last_name: "Carter",
        name_ar: "دانيال كارتر",
        first_name_ar: "دانيال",
        last_name_ar: "كارتر",
        email: "daniel.carter@example.com",
    },
    {
        id: 15,
        name: "Sara Al-Farsi",
        first_name: "Sara",
        last_name: "Al-Farsi",
        name_ar: "سارة الفارسي",
        first_name_ar: "سارة",
        last_name_ar: "الفارسي",
        email: "sara.alfarsi@example.com",
    },
];
